name: Lint, Build, and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20' # Make sure to specify the current version of Go the project is using

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6

    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./...
